export type CalculatorInputType =
  | 'date'
  | 'name'
  | 'plate'
  | 'address'
  | 'phone'
  | 'wedding-date'
  | 'business'
  | 'compatibility'
  | 'name-and-date'
  | 'personal-cycle';

export interface CalculatorConfig {
  id: string;
  slug: string;
  pillar: string;
  icon: string;
  inputType: CalculatorInputType;
  titleKey: string;
  descKey: string;
  category: 'core' | 'lifecycle' | 'practical' | 'relationship';
  meaningSlug?: string;
  relatedSlugs: string[];
}

export const numerologyCalculators: CalculatorConfig[] = [
  {
    id: 'life-path-number',
    slug: 'life-path-number',
    pillar: 'numerology',
    icon: '✨',
    inputType: 'date',
    titleKey: 'calc.lifePath.title',
    descKey: 'calc.lifePath.desc',
    category: 'core',
    meaningSlug: 'life-path-number',
    relatedSlugs: ['destiny-number', 'soul-urge-number', 'personal-year', 'birthday-number'],
  },
  {
    id: 'destiny-number',
    slug: 'destiny-number',
    pillar: 'numerology',
    icon: '🌌',
    inputType: 'name',
    titleKey: 'calc.destiny.title',
    descKey: 'calc.destiny.desc',
    category: 'core',
    meaningSlug: 'destiny-number',
    relatedSlugs: ['life-path-number', 'soul-urge-number', 'personality-number', 'maturity-number'],
  },
  {
    id: 'soul-urge-number',
    slug: 'soul-urge-number',
    pillar: 'numerology',
    icon: '💖',
    inputType: 'name',
    titleKey: 'calc.soulUrge.title',
    descKey: 'calc.soulUrge.desc',
    category: 'core',
    meaningSlug: 'soul-urge-number',
    relatedSlugs: ['personality-number', 'destiny-number', 'life-path-number', 'karmic-lesson-number'],
  },
  {
    id: 'expression-number',
    slug: 'expression-number',
    pillar: 'numerology',
    icon: '🔮',
    inputType: 'name',
    titleKey: 'calc.expression.title',
    descKey: 'calc.expression.desc',
    category: 'core',
    meaningSlug: 'expression-number',
    relatedSlugs: ['destiny-number', 'personality-number', 'life-path-number', 'career-numerology'],
  },
  {
    id: 'birthday-number',
    slug: 'birthday-number',
    pillar: 'numerology',
    icon: '🎂',
    inputType: 'date',
    titleKey: 'calc.birthday.title',
    descKey: 'calc.birthday.desc',
    category: 'core',
    meaningSlug: 'birthday-number',
    relatedSlugs: ['life-path-number', 'lucky-number', 'personal-day', 'pinnacle-number'],
  },
  {
    id: 'personality-number',
    slug: 'personality-number',
    pillar: 'numerology',
    icon: '🎭',
    inputType: 'name',
    titleKey: 'calc.personality.title',
    descKey: 'calc.personality.desc',
    category: 'core',
    meaningSlug: 'personality-number',
    relatedSlugs: ['soul-urge-number', 'destiny-number', 'balance-number', 'life-path-number'],
  },
  {
    id: 'maturity-number',
    slug: 'maturity-number',
    pillar: 'numerology',
    icon: '🌳',
    inputType: 'name-and-date',
    titleKey: 'calc.maturity.title',
    descKey: 'calc.maturity.desc',
    category: 'lifecycle',
    meaningSlug: 'maturity-number',
    relatedSlugs: ['life-path-number', 'destiny-number', 'pinnacle-number', 'challenge-number'],
  },
  {
    id: 'balance-number',
    slug: 'balance-number',
    pillar: 'numerology',
    icon: '⚖️',
    inputType: 'name',
    titleKey: 'calc.balance.title',
    descKey: 'calc.balance.desc',
    category: 'core',
    meaningSlug: 'balance-number',
    relatedSlugs: ['personality-number', 'soul-urge-number', 'destiny-number', 'karmic-lesson-number'],
  },
  {
    id: 'karmic-debt-number',
    slug: 'karmic-debt-number',
    pillar: 'numerology',
    icon: '🔗',
    inputType: 'date',
    titleKey: 'calc.karmicDebt.title',
    descKey: 'calc.karmicDebt.desc',
    category: 'core',
    meaningSlug: 'karmic-debt-number',
    relatedSlugs: ['karmic-lesson-number', 'life-path-number', 'destiny-number', 'challenge-number'],
  },
  {
    id: 'karmic-lesson-number',
    slug: 'karmic-lesson-number',
    pillar: 'numerology',
    icon: '📖',
    inputType: 'name',
    titleKey: 'calc.karmicLesson.title',
    descKey: 'calc.karmicLesson.desc',
    category: 'core',
    meaningSlug: 'karmic-lesson-number',
    relatedSlugs: ['karmic-debt-number', 'destiny-number', 'soul-urge-number', 'balance-number'],
  },
  {
    id: 'challenge-number',
    slug: 'challenge-number',
    pillar: 'numerology',
    icon: '🏔️',
    inputType: 'date',
    titleKey: 'calc.challenge.title',
    descKey: 'calc.challenge.desc',
    category: 'lifecycle',
    meaningSlug: 'challenge-number',
    relatedSlugs: ['pinnacle-number', 'life-path-number', 'maturity-number', 'karmic-debt-number'],
  },
  {
    id: 'pinnacle-number',
    slug: 'pinnacle-number',
    pillar: 'numerology',
    icon: '👑',
    inputType: 'date',
    titleKey: 'calc.pinnacle.title',
    descKey: 'calc.pinnacle.desc',
    category: 'lifecycle',
    meaningSlug: 'pinnacle-number',
    relatedSlugs: ['challenge-number', 'life-path-number', 'personal-year', 'maturity-number'],
  },
  {
    id: 'bridge-number',
    slug: 'bridge-number',
    pillar: 'numerology',
    icon: '🌉',
    inputType: 'name-and-date',
    titleKey: 'calc.bridge.title',
    descKey: 'calc.bridge.desc',
    category: 'core',
    meaningSlug: 'bridge-number',
    relatedSlugs: ['life-path-number', 'destiny-number', 'soul-urge-number', 'personality-number'],
  },
  {
    id: 'essence-number',
    slug: 'essence-number',
    pillar: 'numerology',
    icon: '🌿',
    inputType: 'name',
    titleKey: 'calc.essence.title',
    descKey: 'calc.essence.desc',
    category: 'lifecycle',
    meaningSlug: 'essence-number',
    relatedSlugs: ['personal-year', 'destiny-number', 'life-path-number', 'personal-month'],
  },
  {
    id: 'personal-year',
    slug: 'personal-year',
    pillar: 'numerology',
    icon: '📅',
    inputType: 'personal-cycle',
    titleKey: 'calc.personalYear.title',
    descKey: 'calc.personalYear.desc',
    category: 'lifecycle',
    meaningSlug: 'personal-year',
    relatedSlugs: ['personal-month', 'personal-day', 'life-path-number', 'essence-number'],
  },
  {
    id: 'personal-month',
    slug: 'personal-month',
    pillar: 'numerology',
    icon: '🌙',
    inputType: 'personal-cycle',
    titleKey: 'calc.personalMonth.title',
    descKey: 'calc.personalMonth.desc',
    category: 'lifecycle',
    meaningSlug: 'personal-month',
    relatedSlugs: ['personal-year', 'personal-day', 'life-path-number', 'birthday-number'],
  },
  {
    id: 'personal-day',
    slug: 'personal-day',
    pillar: 'numerology',
    icon: '☀️',
    inputType: 'personal-cycle',
    titleKey: 'calc.personalDay.title',
    descKey: 'calc.personalDay.desc',
    category: 'lifecycle',
    meaningSlug: 'personal-day',
    relatedSlugs: ['personal-month', 'personal-year', 'lucky-number', 'birthday-number'],
  },
  {
    id: 'lucky-number',
    slug: 'lucky-number',
    pillar: 'numerology',
    icon: '🍀',
    inputType: 'date',
    titleKey: 'calc.luckyNumber.title',
    descKey: 'calc.luckyNumber.desc',
    category: 'practical',
    meaningSlug: 'lucky-number',
    relatedSlugs: ['birthday-number', 'life-path-number', 'personal-day', 'vehicle-numerology'],
  },
  {
    id: 'name-numerology',
    slug: 'name-numerology',
    pillar: 'numerology',
    icon: '✍️',
    inputType: 'name',
    titleKey: 'calc.nameNumerology.title',
    descKey: 'calc.nameNumerology.desc',
    category: 'core',
    meaningSlug: 'name-numerology',
    relatedSlugs: ['destiny-number', 'soul-urge-number', 'personality-number', 'business-numerology'],
  },
  {
    id: 'business-numerology',
    slug: 'business-numerology',
    pillar: 'numerology',
    icon: '💼',
    inputType: 'business',
    titleKey: 'calc.businessNumerology.title',
    descKey: 'calc.businessNumerology.desc',
    category: 'practical',
    meaningSlug: 'business-numerology',
    relatedSlugs: ['name-numerology', 'career-numerology', 'phone-numerology', 'destiny-number'],
  },
  {
    id: 'house-numerology',
    slug: 'house-numerology',
    pillar: 'numerology',
    icon: '🏡',
    inputType: 'address',
    titleKey: 'calc.houseNumerology.title',
    descKey: 'calc.houseNumerology.desc',
    category: 'practical',
    meaningSlug: 'house-numerology',
    relatedSlugs: ['vehicle-numerology', 'phone-numerology', 'lucky-number', 'personal-year'],
  },
  {
    id: 'phone-numerology',
    slug: 'phone-numerology',
    pillar: 'numerology',
    icon: '📱',
    inputType: 'phone',
    titleKey: 'calc.phoneNumerology.title',
    descKey: 'calc.phoneNumerology.desc',
    category: 'practical',
    meaningSlug: 'phone-numerology',
    relatedSlugs: ['business-numerology', 'house-numerology', 'lucky-number', 'destiny-number'],
  },
  {
    id: 'vehicle-numerology',
    slug: 'vehicle-numerology',
    pillar: 'numerology',
    icon: '🚗',
    inputType: 'plate',
    titleKey: 'calc.vehicleNumerology.title',
    descKey: 'calc.vehicleNumerology.desc',
    category: 'practical',
    meaningSlug: 'vehicle-numerology',
    relatedSlugs: ['lucky-number', 'house-numerology', 'phone-numerology', 'life-path-number'],
  },
  {
    id: 'marriage-numerology',
    slug: 'marriage-numerology',
    pillar: 'numerology',
    icon: '💍',
    inputType: 'wedding-date',
    titleKey: 'calc.marriageNumerology.title',
    descKey: 'calc.marriageNumerology.desc',
    category: 'relationship',
    meaningSlug: 'marriage-numerology',
    relatedSlugs: ['compatibility-numerology', 'life-path-number', 'personal-year', 'destiny-number'],
  },
  {
    id: 'career-numerology',
    slug: 'career-numerology',
    pillar: 'numerology',
    icon: '🚀',
    inputType: 'name',
    titleKey: 'calc.careerNumerology.title',
    descKey: 'calc.careerNumerology.desc',
    category: 'practical',
    meaningSlug: 'career-numerology',
    relatedSlugs: ['destiny-number', 'life-path-number', 'business-numerology', 'maturity-number'],
  },
  {
    id: 'compatibility-numerology',
    slug: 'compatibility-numerology',
    pillar: 'numerology',
    icon: '💞',
    inputType: 'compatibility',
    titleKey: 'calc.compatibilityNumerology.title',
    descKey: 'calc.compatibilityNumerology.desc',
    category: 'relationship',
    meaningSlug: 'compatibility-numerology',
    relatedSlugs: ['marriage-numerology', 'life-path-number', 'soul-urge-number', 'destiny-number'],
  },
];
